"""init

Revision ID: 2a01f270ed9b
Revises: dc375de6988d
Create Date: 2026-02-19 23:45:19.487714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a01f270ed9b'
down_revision: Union[str, Sequence[str], None] = 'dc375de6988d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genero',
    sa.Column('id_genero', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_genero'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('periodo_escolar',
    sa.Column('id_periodo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_periodo'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('seguro_medico',
    sa.Column('id_seguro_med', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_seguro_med'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('carrera',
    sa.Column('id_carrera', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_escolar.id_periodo'], ),
    sa.PrimaryKeyConstraint('id_carrera'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('estudiantes',
    sa.Column('id_estudiante', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=30), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['genero_id'], ['genero.id_genero'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_estudiante'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('grupos',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['carrera_id'], ['carrera.id_carrera'], ),
    sa.PrimaryKeyConstraint('id_grupo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tutores',
    sa.Column('id_tutor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('clave_sp', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tutor'),
    sa.UniqueConstraint('clave_sp'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('estudiante_grupo',
    sa.Column('id_est_grupo', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id_estudiante'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_est_grupo')
    )
    op.create_table('grupo_tutor',
    sa.Column('id_grupo_tutor', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id_grupo'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id_tutor'], ),
    sa.PrimaryKeyConstraint('id_grupo_tutor')
    )
    op.create_table('seguro_estudiante',
    sa.Column('id_seguro_est', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seguro_med_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('nss', sa.String(length=15), nullable=False),
    sa.Column('estatus', sa.Boolean(), nullable=True),
    sa.Column('clinica', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id_estudiante'], ),
    sa.ForeignKeyConstraint(['seguro_med_id'], ['seguro_medico.id_seguro_med'], ),
    sa.PrimaryKeyConstraint('id_seguro_est'),
    sa.UniqueConstraint('clinica'),
    sa.UniqueConstraint('nss')
    )
    op.create_table('soli_psicopedagogia',
    sa.Column('id_solicitud', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('fecha_soli', sa.String(length=20), nullable=True),
    sa.Column('fecha_lugar', sa.String(length=100), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=50), nullable=False),
    sa.Column('quien_canaliza', sa.String(length=100), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('archivo_pdf', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id_estudiante'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id_tutor'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_table('tutorias',
    sa.Column('id_tutoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('canalizado', sa.Boolean(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('acciones', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id_estudiante'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutores.id_tutor'], ),
    sa.PrimaryKeyConstraint('id_tutoria')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutorias')
    op.drop_table('soli_psicopedagogia')
    op.drop_table('seguro_estudiante')
    op.drop_table('grupo_tutor')
    op.drop_table('estudiante_grupo')
    op.drop_table('tutores')
    op.drop_table('grupos')
    op.drop_table('estudiantes')
    op.drop_table('usuarios')
    op.drop_table('carrera')
    op.drop_table('seguro_medico')
    op.drop_table('roles')
    op.drop_table('periodo_escolar')
    op.drop_table('genero')
    # ### end Alembic commands ###
