"""ajustes modelos para historial y produccion

Revision ID: eda9c5bba78f
Revises: 2a01f270ed9b
Create Date: 2026-02-22 18:14:27.376403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eda9c5bba78f'
down_revision: Union[str, Sequence[str], None] = '2a01f270ed9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carrera', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_index(op.f('alias'), table_name='carrera')
    op.add_column('estudiante_grupo', sa.Column('activo', sa.Boolean(), nullable=False))
    op.add_column('estudiantes', sa.Column('estado', sa.String(length=20), nullable=False))
    op.drop_column('estudiantes', 'activo')
    op.add_column('grupo_tutor', sa.Column('activo', sa.Boolean(), nullable=False))
    op.alter_column('grupos', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_index(op.f('nombre'), table_name='grupos')
    op.drop_index(op.f('alias'), table_name='periodo_escolar')
    op.add_column('seguro_estudiante', sa.Column('activo', sa.Boolean(), nullable=False))
    op.alter_column('seguro_estudiante', 'clinica',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('clinica'), table_name='seguro_estudiante')
    op.drop_index(op.f('nss'), table_name='seguro_estudiante')
    op.alter_column('soli_psicopedagogia', 'fecha_soli',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.add_column('tutores', sa.Column('estado', sa.String(length=20), nullable=False))
    op.drop_column('tutores', 'activo')
    op.add_column('tutorias', sa.Column('estado', sa.String(length=20), nullable=False))
    op.add_column('usuarios', sa.Column('estado', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'estado')
    op.drop_column('tutorias', 'estado')
    op.add_column('tutores', sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('tutores', 'estado')
    op.alter_column('soli_psicopedagogia', 'fecha_soli',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('nss'), 'seguro_estudiante', ['nss'], unique=True)
    op.create_index(op.f('clinica'), 'seguro_estudiante', ['clinica'], unique=True)
    op.alter_column('seguro_estudiante', 'clinica',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
    op.drop_column('seguro_estudiante', 'activo')
    op.create_index(op.f('alias'), 'periodo_escolar', ['alias'], unique=True)
    op.create_index(op.f('nombre'), 'grupos', ['nombre'], unique=True)
    op.alter_column('grupos', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('grupo_tutor', 'activo')
    op.add_column('estudiantes', sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('estudiantes', 'estado')
    op.drop_column('estudiante_grupo', 'activo')
    op.create_index(op.f('alias'), 'carrera', ['alias'], unique=True)
    op.alter_column('carrera', 'activo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
