from .usuarios import Usuarios
from .roles import Roles
from .tutores import Tutores
from .estudiantes import Estudiantes
from .seguro_estudiante import SeguroEstudiante
from .seguro_medico import SeguroMedico
from .grupos import Grupos
from .grupo_tutor import GrupoTutor
from .estudiante_grupo import EstudianteGrupo
from .carreras import Carreras
from .periodo_escolar import PeriodoEscolar
from .tutorias import Tutorias
from .soli_psicopedagogia import SoliPsicopedagogia
from .genero import Genero